---
version: "3"

services:
  web:
    build: .
    command: >
     bash -c "python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code/
    environment:
      - DJ_SECRET_KEY=k5mx0y3pev1z_kjw
      - DJ_DEBUG=true
    expose:
      - "8000"
    ports:
      - 8000:8000
    networks:
      - backend

  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./frontend/app:/app
    environment:
      - API_BASE_URL=http://web:8000/v1
    expose:
      - "3000"
    ports:
      - 3000:3000
    networks:
      - backend
    depends_on:
      - web

networks:
  backend:
    name: backend
    driver: 'bridge'
    external: true
