---
version: "3"

services:
  web:
    build: .
    command: sleep 365d
    volumes:
      - ./:/code/
    environment:
      - DJ_SECRET_KEY=k5mx0y3pev1z_kjw
      - DJ_DEBUG=true
    expose:
      - "8000"
    ports:
      - 8000:8000
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: 'bridge'
    external: true
