# Generated by Django 4.0.6 on 2023-12-31 14:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeathCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.CharField(max_length=256)),
                ("timestamp", models.DateTimeField()),
                ("source", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="HeathCheckPlugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("status", models.IntegerField()),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identifier", models.UUIDField(default=uuid.uuid4)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["identifier"], name="monitoring__identif_e7fad5_idx"
            ),
        ),
        migrations.AddField(
            model_name="heathcheckplugin",
            name="health_check",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="monitoring.heathcheck"
            ),
        ),
        migrations.AddField(
            model_name="heathcheck",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="monitoring.service"
            ),
        ),
        migrations.AddIndex(
            model_name="heathcheckplugin",
            index=models.Index(fields=["name"], name="monitoring__name_393519_idx"),
        ),
        migrations.AddIndex(
            model_name="heathcheck",
            index=models.Index(
                fields=["timestamp"], name="monitoring__timesta_daf439_idx"
            ),
        ),
    ]
